"""Add relationship to user

Revision ID: ef8394fa83b5
Revises: f31b742a20e8
Create Date: 2022-08-12 08:20:08.238543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef8394fa83b5'
down_revision = 'f31b742a20e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'author', 'user', ['user_id'], ['id'])
    op.add_column('book', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'book', 'user', ['user_id'], ['id'])
    op.add_column('category', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'category', 'user', ['user_id'], ['id'])
    op.add_column('genre', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'genre', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genre', type_='foreignkey')
    op.drop_column('genre', 'user_id')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'user_id')
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'user_id')
    op.drop_constraint(None, 'author', type_='foreignkey')
    op.drop_column('author', 'user_id')
    # ### end Alembic commands ###
